---
- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo 
  remote_user: ansible

  tasks:
    - name: add to grub 
      lineinfile:
        dest: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.*{{ item.key }})\"[^\"]+)(\".*)'
        line: '\1 {{ item.key }}={{ item.val }}\2'
        state: present
        backrefs: yes
      loop:
        - { key: 'net.ifnames', val: '0' }
        - { key: 'biosdevname', val: '0' }
      notify: update grub


    - name: update grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

