---
- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo 
  remote_user: ansible

  tasks:
    - name: remove httpd
      yum:
        name: httpd
        state: absent

    - name: remove index
      file:
        state: absent
        path: /var/www/html/index.html

    - name: remove ports
      firewalld:
        port: "{{ item.port }}"
        permanent: "{{ item.permanent }}"
        zone: public
        state: disabled
      with_items:
        - { port: '80/tcp', permanent: true }
        - { port: '443/tcp', permanent: true }   
      notify: firewalld restart
            

  handlers:
    - name: firewalld restart
      service: 
        name: firewalld
        state: restarted
        