---
# vars file for ftp
ftp_config: vsftpd.conf
ftp_config_dest: /etc/vsftpd/


anonymous_enable: "YES"
chroot_local_user: "YES"
anon_upload_enable: "YES"
listen_ipv6: "no"
listen: "YES"
connect_from_port_20: "YES"
xferlog_enable: "YES"
dirmessage_enable: "YES"
local_umask: "022"
write_enable: "YES"
local_enable: "YES"
pasv_enable: "YES"



ftp1_port: 20/tcp
ftp2_port: 21/tcp
rule_permanent: true