---
# tasks file for apache

- name: install httpd
  yum:
    name: httpd
    state: latest
  notify:
    - httpd restEnabled

- name: index file
  copy:
    src: "{{ html_file }}"
    dest: "{{ html_dest }}/index.html"
    owner: apache
    group: apache
    mode: 0644
  notify:  
  - httpd restEnabled  

- name: css file
  template:
    dest: "{{ html_dest }}/main.css"
    src: main.css.j2
    owner: apache
    group: apache
    mode: 0644
  notify:  
  - httpd restEnabled   

- name: httpd's ports
  firewalld:
    port: "{{ item.port }}"
    permanent: "{{ item.permanent }}"
    state: enabled
  with_items:
    - { port: "{{ http_port }}", permanent: "{{ rule_permanent }}" }
    - { port: "{{ https_port }}", permanent: "{{ rule_permanent }}" }   
  notify: firewalld restart  


