---
- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo 
  remote_user: ansible

  tasks:
    - name: add to grub 
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".*'
        insertbefore: BOF
        line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"'


    - name: update grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

