---
- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo 
  remote_user: ansible
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: latest
      notify:
        - httpd restEnabled
      
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: file content
      lineinfile:
        dest: /var/www/html/index.html
        insertbefore: BOF
        line: "Welcome to my web server"

    - name: httpd's ports
      firewalld:
        port: "{{ item.port }}"
        permanent: "{{ item.permanent }}"
        state: enabled
      with_items:
        - { port: '80/tcp', permanent: true }
        - { port: '443/tcp', permanent: true }   
      notify: firewalld restart


  handlers: 
    - name: httpd restEnabled
      service:
        name: httpd
        state: restarted      
        enabled: yes

    - name: firewalld restart
      service: 
        name: firewalld
        state: restarted
        enabled: yes    

