---
- hosts: nodes
  become: yes
  become_user: root
  become_method: sudo 
  remote_user: ansible 
  vars_files:
    - .pass_one
   

  tasks:
    - name: create new users
      user:
        name: "{{ item.username }}" 
        create_home: yes 
        state: present 
        comment: "{{ item.username }}@example.com"
        shell: /bin/bash 
        password: "{{ item.pass | password_hash('sha512') }}"
        password: "{{ password[item['username']] | password_hash('sha512') }}"
        update_password: on_create
      #no_log: true   
      loop:
        - username: 'Alice'
        - username: 'Bob'
        - username: 'Carol'

